// Autogenerated image manifest for local images
// Imports and arrays grouped by category

// Bridal Makeup
import bm_004 from '@/images/bridal_makeup/bridal_makeup_004.jpg';
import bm_005 from '@/images/bridal_makeup/bridal_makeup_005.jpg';
import bm_006 from '@/images/bridal_makeup/bridal_makeup_006.jpg';
import bm_007 from '@/images/bridal_makeup/bridal_makeup_007.jpg';
import bm_009 from '@/images/bridal_makeup/bridal_makeup_009.jpg';
import bm_012 from '@/images/bridal_makeup/bridal_makeup_012.jpg';
import bm_013 from '@/images/bridal_makeup/bridal_makeup_013.jpg';
import bm_014 from '@/images/bridal_makeup/bridal_makeup_014.jpg';
import bm_016 from '@/images/bridal_makeup/bridal_makeup_016.jpg';
import bm_017 from '@/images/bridal_makeup/bridal_makeup_017.jpg';
import bm_020 from '@/images/bridal_makeup/bridal_makeup_020.jpg';
import bm_021 from '@/images/bridal_makeup/bridal_makeup_021.jpg';
import bm_026 from '@/images/bridal_makeup/bridal_makeup_026.jpg';
import bm_029 from '@/images/bridal_makeup/bridal_makeup_029.jpg';

export const BridalMakeupImages = [
  bm_004, bm_005, bm_006, bm_007, bm_009, bm_012, bm_013, bm_014, bm_016, bm_017, bm_020, bm_021, bm_026, bm_029
] as const;

// Bridal Portrait
import bp_001 from '@/images/bridal_portrait/bridal_portrait_001.jpg';
import bp_002 from '@/images/bridal_portrait/bridal_portrait_002.jpg';
import bp_003 from '@/images/bridal_portrait/bridal_portrait_003.jpg';
import bp_004 from '@/images/bridal_portrait/bridal_portrait_004.jpg';
import bp_005 from '@/images/bridal_portrait/bridal_portrait_005.jpg';
import bp_006 from '@/images/bridal_portrait/bridal_portrait_006.jpg';
import bp_007 from '@/images/bridal_portrait/bridal_portrait_007.jpg';
import bp_008 from '@/images/bridal_portrait/bridal_portrait_008.jpg';
import bp_009 from '@/images/bridal_portrait/bridal_portrait_009.jpg';
import bp_010 from '@/images/bridal_portrait/bridal_portrait_010.jpg';
import bp_011 from '@/images/bridal_portrait/bridal_portrait_011.jpg';
import bp_012 from '@/images/bridal_portrait/bridal_portrait_012.jpg';
import bp_013 from '@/images/bridal_portrait/bridal_portrait_013.jpg';
import bp_014 from '@/images/bridal_portrait/bridal_portrait_014.jpg';
import bp_015 from '@/images/bridal_portrait/bridal_portrait_015.jpg';
import bp_016 from '@/images/bridal_portrait/bridal_portrait_016.jpg';
import bp_017 from '@/images/bridal_portrait/bridal_portrait_017.jpg';
import bp_018 from '@/images/bridal_portrait/bridal_portrait_018.jpg';
import bp_019 from '@/images/bridal_portrait/bridal_portrait_019.jpg';
import bp_020 from '@/images/bridal_portrait/bridal_portrait_020.jpeg';
import bp_021 from '@/images/bridal_portrait/bridal_portrait_021.jpg';
import bp_022 from '@/images/bridal_portrait/bridal_portrait_022.jpg';
import bp_023 from '@/images/bridal_portrait/bridal_portrait_023.jpg';
import bp_024 from '@/images/bridal_portrait/bridal_portrait_024.jpg';
import bp_025 from '@/images/bridal_portrait/bridal_portrait_025.jpg';
import bp_026 from '@/images/bridal_portrait/bridal_portrait_026.jpg';

export const BridalPortraitImages = [
  bp_001, bp_002, bp_003, bp_004, bp_005, bp_006, bp_007, bp_008, bp_009, bp_010, bp_011, bp_012, bp_013, bp_014, bp_015,
  bp_016, bp_017, bp_018, bp_019, bp_020, bp_021, bp_022, bp_023, bp_024, bp_025, bp_026
] as const;

// Wedding Ceremony
import wc_001 from '@/images/wedding_ceremony/wedding_ceremony_001.jpg';
import wc_002 from '@/images/wedding_ceremony/wedding_ceremony_002.jpg';
import wc_003 from '@/images/wedding_ceremony/wedding_ceremony_003.jpg';
import wc_004 from '@/images/wedding_ceremony/wedding_ceremony_004.jpg';
import wc_005 from '@/images/wedding_ceremony/wedding_ceremony_005.jpg';
import wc_006 from '@/images/wedding_ceremony/wedding_ceremony_006.jpg';
import wc_007 from '@/images/wedding_ceremony/wedding_ceremony_007.jpg';
import wc_008 from '@/images/wedding_ceremony/wedding_ceremony_008.jpg';
import wc_009 from '@/images/wedding_ceremony/wedding_ceremony_009.jpg';
import wc_010 from '@/images/wedding_ceremony/wedding_ceremony_010.jpg';
import wc_011 from '@/images/wedding_ceremony/wedding_ceremony_011.jpg';
import wc_012 from '@/images/wedding_ceremony/wedding_ceremony_012.jpg';
import wc_013 from '@/images/wedding_ceremony/wedding_ceremony_013.jpg';
import wc_014 from '@/images/wedding_ceremony/wedding_ceremony_014.jpg';
import wc_015 from '@/images/wedding_ceremony/wedding_ceremony_015.jpg';
import wc_016 from '@/images/wedding_ceremony/wedding_ceremony_016.jpg';
import wc_017 from '@/images/wedding_ceremony/wedding_ceremony_017.jpg';
import wc_018 from '@/images/wedding_ceremony/wedding_ceremony_018.jpg';
import wc_019 from '@/images/wedding_ceremony/wedding_ceremony_019.jpg';
import wc_020 from '@/images/wedding_ceremony/wedding_ceremony_020.jpg';
import wc_021 from '@/images/wedding_ceremony/wedding_ceremony_021.jpg';
import wc_022 from '@/images/wedding_ceremony/wedding_ceremony_022.jpg';
import wc_023 from '@/images/wedding_ceremony/wedding_ceremony_023.jpg';
import wc_024 from '@/images/wedding_ceremony/wedding_ceremony_024.jpg';
import wc_025 from '@/images/wedding_ceremony/wedding_ceremony_025.jpg';
import wc_026 from '@/images/wedding_ceremony/wedding_ceremony_026.jpg';
import wc_027 from '@/images/wedding_ceremony/wedding_ceremony_027.jpg';
import wc_028 from '@/images/wedding_ceremony/wedding_ceremony_028.jpg';
import wc_029 from '@/images/wedding_ceremony/wedding_ceremony_029.jpg';

export const WeddingCeremonyImages = [
  wc_001, wc_002, wc_003, wc_004, wc_005, wc_006, wc_007, wc_008, wc_009, wc_010, wc_011, wc_012, wc_013, wc_014, wc_015,
  wc_016, wc_017, wc_018, wc_019, wc_020, wc_021, wc_022, wc_023, wc_024, wc_025, wc_026, wc_027, wc_028, wc_029
] as const;

// Wedding Couple
import wco_011 from '@/images/wedding_couple/wedding_couple_011.jpg';
import wco_012 from '@/images/wedding_couple/wedding_couple_012.jpg';
import wco_013 from '@/images/wedding_couple/wedding_couple_013.jpg';
import wco_014 from '@/images/wedding_couple/wedding_couple_014.jpg';
import wco_015 from '@/images/wedding_couple/wedding_couple_015.jpg';
import wco_016 from '@/images/wedding_couple/wedding_couple_016.jpg';
import wco_017 from '@/images/wedding_couple/wedding_couple_017.jpg';
import wco_018 from '@/images/wedding_couple/wedding_couple_018.jpg';
import wco_020 from '@/images/wedding_couple/wedding_couple_020.jpg';
import wco_022 from '@/images/wedding_couple/wedding_couple_022.jpg';
import wco_023 from '@/images/wedding_couple/wedding_couple_023.jpg';
import wco_024 from '@/images/wedding_couple/wedding_couple_024.jpg';
import wco_025 from '@/images/wedding_couple/wedding_couple_025.jpg';
import wco_026 from '@/images/wedding_couple/wedding_couple_026.jpg';
import wco_027 from '@/images/wedding_couple/wedding_couple_027.jpg';
import wco_028 from '@/images/wedding_couple/wedding_couple_028.jpg';
// Note: wedding_couple_029/030 not present in images folder; skipped

export const WeddingCoupleImages = [
  wco_011, wco_012, wco_013, wco_014, wco_015, wco_016, wco_017, wco_018, wco_020, wco_022, wco_023, wco_024, wco_025, wco_026, wco_027, wco_028
] as const;

// Wedding Details
import wd_001 from '@/images/wedding_details/wedding_details_001.jpg';
import wd_002 from '@/images/wedding_details/wedding_details_002.jpg';
import wd_003 from '@/images/wedding_details/wedding_details_003.jpg';
import wd_004 from '@/images/wedding_details/wedding_details_004.jpg';
import wd_005 from '@/images/wedding_details/wedding_details_005.jpg';
import wd_006 from '@/images/wedding_details/wedding_details_006.jpg';
import wd_007 from '@/images/wedding_details/wedding_details_007.jpg';
import wd_008 from '@/images/wedding_details/wedding_details_008.jpg';
import wd_009 from '@/images/wedding_details/wedding_details_009.jpg';
import wd_010 from '@/images/wedding_details/wedding_details_010.jpg';
import wd_011 from '@/images/wedding_details/wedding_details_011.jpg';
import wd_012 from '@/images/wedding_details/wedding_details_012.jpg';
import wd_013 from '@/images/wedding_details/wedding_details_013.jpg';
import wd_014 from '@/images/wedding_details/wedding_details_014.jpg';
import wd_015 from '@/images/wedding_details/wedding_details_015.jpg';
import wd_016 from '@/images/wedding_details/wedding_details_016.jpg';
import wd_017 from '@/images/wedding_details/wedding_details_017.jpg';
import wd_018 from '@/images/wedding_details/wedding_details_018.jpg';
import wd_019 from '@/images/wedding_details/wedding_details_019.jpg';
import wd_020 from '@/images/wedding_details/wedding_details_020.jpg';
import wd_021 from '@/images/wedding_details/wedding_details_021.jpg';
import wd_022 from '@/images/wedding_details/wedding_details_022.jpg';
import wd_023 from '@/images/wedding_details/wedding_details_023.jpg';
import wd_024 from '@/images/wedding_details/wedding_details_024.jpg';
import wd_025 from '@/images/wedding_details/wedding_details_025.jpg';
import wd_026 from '@/images/wedding_details/wedding_details_026.jpg';
import wd_027 from '@/images/wedding_details/wedding_details_027.jpg';
import wd_028 from '@/images/wedding_details/wedding_details_028.jpg';
import wd_029 from '@/images/wedding_details/wedding_details_029.jpg';
import wd_030 from '@/images/wedding_details/wedding_details_030.jpg';

export const WeddingDetailsImages = [
  wd_001, wd_002, wd_003, wd_004, wd_005, wd_006, wd_007, wd_008, wd_009, wd_010, wd_011, wd_012, wd_013, wd_014, wd_015,
  wd_016, wd_017, wd_018, wd_019, wd_020, wd_021, wd_022, wd_023, wd_024, wd_025, wd_026, wd_027, wd_028, wd_029, wd_030
] as const;

export type CategoryKey = 'Bridal Makeup' | 'Portraits' | 'Ceremonies' | 'Details';

export const CategoryMap: Record<CategoryKey, readonly any[]> = {
  'Bridal Makeup': BridalMakeupImages,
  'Portraits': BridalPortraitImages.length ? BridalPortraitImages : WeddingCoupleImages,
  'Ceremonies': WeddingCeremonyImages,
  'Details': WeddingDetailsImages,
};
